# Unfortunately, the bsddb module on Travis-CI's virtualenv is broken...
# This means that we always need to manually install BSD-DB, even when we're
# running the tests under Python 2 where normally we should be able to just use
# the bsddb module in the standard library. If this wasn't the case, we'd guard
# the manual BSD-DB installation with a TRAVIS_PYTHON_VERSION check.

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - BERKELEYDB_DIR=/usr

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libdb5.1-dev

install:
  - pip install -U setuptools
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install -r requirements.pip
  - pip install -r requirements-py3.pip

  # Coverage 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

script: coverage run --source=gutenberg -m nose

after_success:
  - coverage report
  - pip install coveralls
  - coveralls
